version: '3.8'

services:
  app:
    user: "${UID}:${GID}"
    container_name: junction
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - ARCH=amd64      # markus change to "arm64v8"
        - PYTHON_VERSION=3.11
    tty: true
    stdin_open: true
    command: bash
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./prep.sh:/app/prep.sh
      - node_modules:/app/frontend/node_modules

      # Neovim stuff
      - "./nvim-linux64/:/root/" # neovim binary
      - "~/bin/:/root/scripts/" # some script to make my config work
      - "./nvim_config/:/root/nvim/" # neovim config
      - "./bashrc/:/root/.bashrc" # set path variables + add shortcut to start nvim
    ports:
      - "5173:5173" #vite dev port
      - "8000:8000" #fastapi server port
      
volumes:
  node_modules:
